// scripts/seed_parametros_completo.js
// Inserta/actualiza todos los parámetros de laboratorio con sus tipos asociados
require('dotenv').config();

const { connectDB } = require('../model/db');
const models = require('../model/initModels');

async function main() {
    try {
        await connectDB({ alter: false });

        // Mapeo de tipos (IDs)
        const LABORATORIO = 1;
        const IMAGEN = 2;
        const SANGRE = 1;
        const ECOGRAFIA = 2;
        const TEJIDO = 3;

        const parametros = [
            // Parámetros de Laboratorio - Sangre
            {
                codigo: 'GLUCOSA',
                nombre: 'Glucosa',
                unidad: 'mg/dL',
                ref_min: 70,
                ref_max: 100,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: SANGRE,
                notas: 'Glucemia en ayunas',
            },
            {
                codigo: 'COLESTEROL_TOTAL',
                nombre: 'Colesterol Total',
                unidad: 'mg/dL',
                ref_min: null,
                ref_max: 200,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: SANGRE,
                notas: 'Colesterol total sérico',
            },
            {
                codigo: 'TRIGLICERIDOS',
                nombre: 'Triglicéridos',
                unidad: 'mg/dL',
                ref_min: null,
                ref_max: 150,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: SANGRE,
                notas: 'Triglicéridos séricos',
            },
            {
                codigo: 'HB',
                nombre: 'Hemoglobina (HB)',
                unidad: 'g/dL',
                ref_min: 12,
                ref_max: 16,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: SANGRE,
                notas: 'Hemoglobina en sangre completa',
            },
            {
                codigo: 'UREMIA',
                nombre: 'Uremia / Urea',
                unidad: 'mg/dL',
                ref_min: 10,
                ref_max: 50,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: SANGRE,
                notas: 'Nitrógeno ureico en sangre',
            },
            {
                codigo: 'CREA',
                nombre: 'Creatinina (CREA)',
                unidad: 'mg/dL',
                ref_min: 0.6,
                ref_max: 1.2,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: SANGRE,
                notas: 'Creatinina sérica',
            },
            {
                codigo: 'INR',
                nombre: 'INR',
                unidad: 'ratio',
                ref_min: 0.8,
                ref_max: 1.2,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: SANGRE,
                notas: 'Razón internacional normalizada',
            },
            {
                codigo: 'PROTROMBINA',
                nombre: 'Protrombina (Actividad %)',
                unidad: '%',
                ref_min: 70,
                ref_max: 100,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: SANGRE,
                notas: 'Actividad protrombínica',
            },
            {
                codigo: 'SODIO',
                nombre: 'Sodio',
                unidad: 'mEq/L',
                ref_min: 135,
                ref_max: 145,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: SANGRE,
                notas: 'Sodio sérico',
            },
            {
                codigo: 'POTASIO',
                nombre: 'Potasio',
                unidad: 'mEq/L',
                ref_min: 3.5,
                ref_max: 5.0,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: SANGRE,
                notas: 'Potasio sérico',
            },
            {
                codigo: 'HTO',
                nombre: 'Hematocrito (HTO)',
                unidad: '%',
                ref_min: 36,
                ref_max: 46,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: SANGRE,
                notas: 'Hematocrito en sangre completa',
            },
            {
                codigo: 'PLAQUETAS',
                nombre: 'Plaquetas',
                unidad: 'x10³/µL',
                ref_min: 150,
                ref_max: 400,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: SANGRE,
                notas: 'Recuento plaquetario',
            },
            {
                codigo: 'VIT_D',
                nombre: 'Vitamina D (25-OH)',
                unidad: 'ng/mL',
                ref_min: 30,
                ref_max: 100,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: SANGRE,
                notas: '25-hidroxivitamina D',
            },
            {
                codigo: 'VIT_B12',
                nombre: 'Vitamina B12',
                unidad: 'pg/mL',
                ref_min: 200,
                ref_max: 900,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: SANGRE,
                notas: 'Cobalamina sérica',
            },
            {
                codigo: 'ALBUMINA',
                nombre: 'Albúmina',
                unidad: 'g/dL',
                ref_min: 3.5,
                ref_max: 5.0,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: SANGRE,
                notas: 'Albúmina sérica',
            },
            {
                codigo: 'CALCIO',
                nombre: 'Calcio (corregido)',
                unidad: 'mg/dL',
                ref_min: 8.5,
                ref_max: 10.5,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: SANGRE,
                notas: 'Calcio sérico corregido por albúmina',
            },
            {
                codigo: 'MAGNESIO',
                nombre: 'Magnesio (plasmático)',
                unidad: 'mg/dL',
                ref_min: 1.7,
                ref_max: 2.2,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: SANGRE,
                notas: 'Magnesio plasmático',
            },
            {
                codigo: 'PTH',
                nombre: 'PTH',
                unidad: 'pg/mL',
                ref_min: 10,
                ref_max: 65,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: SANGRE,
                notas: 'Paratohormona intacta',
            },
            {
                codigo: 'TSH',
                nombre: 'TSH',
                unidad: 'µUI/mL',
                ref_min: 0.4,
                ref_max: 4.0,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: SANGRE,
                notas: 'Hormona estimulante de la tiroides',
            },
            {
                codigo: 'T4L',
                nombre: 'T4 libre (T4L)',
                unidad: 'ng/dL',
                ref_min: 0.8,
                ref_max: 1.8,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: SANGRE,
                notas: 'Tiroxina libre',
            },
            {
                codigo: 'HIERRO',
                nombre: 'Hierro (Fe)',
                unidad: 'µg/dL',
                ref_min: 50,
                ref_max: 150,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: SANGRE,
                notas: 'Hierro sérico',
            },
            {
                codigo: 'TRANSFERRINA',
                nombre: 'Transferrina',
                unidad: 'mg/dL',
                ref_min: 200,
                ref_max: 360,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: SANGRE,
                notas: 'Transferrina sérica',
            },
            {
                codigo: 'SAT_TRANSFERRINA',
                nombre: '% Saturación de transferrina',
                unidad: '%',
                ref_min: 20,
                ref_max: 50,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: SANGRE,
                notas: 'Porcentaje de saturación de transferrina',
            },

            // Parámetros de Imagen - Ecografía
            {
                codigo: 'VEL_SENAL_AD',
                nombre: 'Velocidad 1.ª señal aD',
                unidad: 'm/s',
                ref_min: null,
                ref_max: null,
                tipo_examen_id: IMAGEN,
                tipo_muestra_id: ECOGRAFIA,
                notas: 'Velocidad de la primera señal de ultrasonido axial distal',
            },
            {
                codigo: 'VEL_MODO_A0',
                nombre: 'Velocidad modo A0',
                unidad: 'm/s',
                ref_min: null,
                ref_max: null,
                tipo_examen_id: IMAGEN,
                tipo_muestra_id: ECOGRAFIA,
                notas: 'Velocidad en modo A0',
            },
            {
                codigo: 'ESPESOR_CORTICAL',
                nombre: 'Espesor cortical',
                unidad: 'mm',
                ref_min: null,
                ref_max: null,
                tipo_examen_id: IMAGEN,
                tipo_muestra_id: ECOGRAFIA,
                notas: 'Grosor del hueso cortical',
            },
            {
                codigo: 'POROSIDAD_CORTICAL',
                nombre: 'Porosidad cortical',
                unidad: '%',
                ref_min: null,
                ref_max: null,
                tipo_examen_id: IMAGEN,
                tipo_muestra_id: ECOGRAFIA,
                notas: 'Porcentaje de porosidad cortical',
            },
            {
                codigo: 'MAX_INVERSO',
                nombre: 'Máximo del inverso (0–1)',
                unidad: null,
                ref_min: 0,
                ref_max: 1,
                tipo_examen_id: IMAGEN,
                tipo_muestra_id: ECOGRAFIA,
                notas: 'Valor normalizado del máximo del inverso',
            },
            {
                codigo: 'DIF_MAX',
                nombre: 'Diferencia entre máx (0–1)',
                unidad: null,
                ref_min: 0,
                ref_max: 1,
                tipo_examen_id: IMAGEN,
                tipo_muestra_id: ECOGRAFIA,
                notas: 'Diferencia normalizada entre máximos',
            },
            {
                codigo: 'INTENSIDAD_BAJA_K',
                nombre: 'Intensidad baja-k (0–1)',
                unidad: null,
                ref_min: 0,
                ref_max: 1,
                tipo_examen_id: IMAGEN,
                tipo_muestra_id: ECOGRAFIA,
                notas: 'Intensidad normalizada en baja frecuencia',
            },
            {
                codigo: 'ESPESOR_TEJIDO_BLANDO',
                nombre: 'Espesor de tejido blando',
                unidad: 'mm',
                ref_min: null,
                ref_max: null,
                tipo_examen_id: IMAGEN,
                tipo_muestra_id: ECOGRAFIA,
                notas: 'Grosor del tejido blando sobre el hueso',
            },

            // Parámetros de Laboratorio - Tejido (espectroscopia FTIR)
            {
                codigo: 'AMIDA_I',
                nombre: 'Amida I (colágeno)',
                unidad: null,
                ref_min: null,
                ref_max: null,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: TEJIDO,
                notas: 'Banda proteica; usada en índices de colágeno. Banda espectral: 1710–1590 cm⁻¹.',
            },
            {
                codigo: 'AMIDA_II',
                nombre: 'Amida II (colágeno)',
                unidad: null,
                ref_min: null,
                ref_max: null,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: TEJIDO,
                notas: 'Complementa Amida I (marcador proteico). Banda espectral aproximada: ~1580–1500 cm⁻¹.',
            },
            {
                codigo: 'FOSFATOS_APATITA',
                nombre: 'Fosfatos (apatita)',
                unidad: null,
                ref_min: null,
                ref_max: null,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: TEJIDO,
                notas: 'Fase mineral. Bandas: ν₃ 1110–940 cm⁻¹; ν₄ doblete 603 y 565 cm⁻¹. Picos 603/565 usados para cristalinidad (IRSF).',
            },
            {
                codigo: 'CARBONATOS_APATITA',
                nombre: 'Carbonatos (apatita)',
                unidad: null,
                ref_min: null,
                ref_max: null,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: TEJIDO,
                notas: 'Sustitución carbonatada (tipo A/B). Bandas: ν₃ 1455–1415 cm⁻¹; ν₂ ~872 cm⁻¹.',
            },
            {
                codigo: 'PO4_CO3',
                nombre: 'Relación fosfato/carbonato',
                unidad: null,
                ref_min: null,
                ref_max: null,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: TEJIDO,
                notas: 'Cociente composicional PO₄/CO₃ basado en áreas/alturas integradas de bandas; depende del protocolo de integración.',
            },
            {
                codigo: 'CI_IRSF',
                nombre: 'Índice de cristalinidad (IRSF)',
                unidad: null,
                ref_min: null,
                ref_max: null,
                tipo_examen_id: LABORATORIO,
                tipo_muestra_id: TEJIDO,
                notas: 'Definido como (altura 565 + 603) / valle entre ambas; mayor CI ⇒ mayor cristalinidad. Sensible al protocolo/preparación.',
            },
        ];

        for (const data of parametros) {
            await models.ParametroLab.upsert(data);
            console.log(
                `✔️  Upsert parametro_lab: ${data.codigo} (${data.nombre})`
            );
        }

        console.log(
            `✅ Seed de parametro_lab completado (${parametros.length} parámetros)`
        );
        process.exit(0);
    } catch (err) {
        console.error('❌ Error en seed parametro_lab:', err);
        process.exit(1);
    }
}

main();
